### ISSUE TITLE
Working perfect after adding 3 dots to sw.js

### ISSUE THREAD

**Issue by reszel** [suisuyy/sreadium#1]
Just add Dot before Slash:
'/images/covers/cover8.jpg'   -->   './images/covers/cover8.jpg'	
'/font-faces/fonts.js'   -->   './font-faces/fonts.js'  
'/fonts/glyphicons-halflings-regular.woff2'   -->   './fonts/glyphicons-halflings-regular.woff2'

PS. Generated 404 ERRORS every time in sw.js on: 
https://cirkel.danskyrka.eu/wp-content/uploads/2022/08/sreadium/?

**Comment by suisuyy** [comment]
yeah, i miss these 3 dot, will add soon, Dot before slash is much better

**Comment by suisuyy** [comment]
now sreadium works normally at any path
